### ISSUE TITLE
No settings page

### ISSUE THREAD

**Issue by ElFDA** [kconger/MiSTer_web2rgbmatrix#15]
Hello!
After flashing latest OTA update the Settings page is white
I also reflashed but nothing is displayed on Chrome and Firefox

**Comment by venice1200** [comment]
Could you clear your Browser Cache and try again?!

**Comment by ElFDA** [comment]
Already done, same problem even on different device (notebook with linux and android smartphone)

**Comment by kconger** [comment]
I can confirm I see the issue here.  I'll see if I can get it fixed tonight.

**Comment by kconger** [comment]
Did some troubleshooting this morning, it appears a library/BSP update introduced this bug.  If I compile the previous version with the latest libraries and BSP I also have this error as well.  This may take a bit to track down.

**Comment by kconger** [comment]
Rebuilt today with latest libraries and everything seems to work again.  Please try today's release and let me know. You may need to flash over USB if your OTA isn't working.

**Comment by venice1200** [comment]
Version 20231119 works fine for me.
