### ISSUE TITLE
3D printed parts

### ISSUE THREAD

**Issue by Numbski** [kconger/MiSTer_web2rgbmatrix#2]
You had to know someone was going to ask about the parts too, right?  :)

Your demo display looks pretty awesome, so I would like to replicate it.

**Comment by kconger** [comment]
> You had to know someone was going to ask about the parts too, right? :)
> 
> Your demo display looks pretty awesome, so I would like to replicate it.

Thank you!  

Sure, I'll add the models and some details.  I'll close this when they are up.

**Comment by kconger** [comment]
fc6e275021d849abf0ab04adca79f86a5fbbc737
