### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by BulletMag** [kconger/MiSTer_web2rgbmatrix#4]
I have erased Arduino IDE completely but I still get the following error when trying to compile...

In file included from c:\Users\craig\Documents\Arduino\libraries\FastLED\src/FastLED.h:67:0,
                 from C:\Users\craig\Downloads\MiSTer_web2rgbmatrix-master (1)\MiSTer_web2rgbmatrix-master\arduino\web2rgbmatrix\web2rgbmatrix.ino:26:
c:\Users\craig\Documents\Arduino\libraries\FastLED\src/fastspi.h:145:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^
In file included from C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi\src/WiFi.h:31:0,
                 from c:\Users\craig\Documents\Arduino\libraries\ESP32FTPServer-master\src/ESP32FtpServer.h:41,
                 from C:\Users\craig\Downloads\MiSTer_web2rgbmatrix-master (1)\MiSTer_web2rgbmatrix-master\arduino\web2rgbmatrix\web2rgbmatrix.ino:23:
C:\Users\craig\Downloads\MiSTer_web2rgbmatrix-master (1)\MiSTer_web2rgbmatrix-master\arduino\web2rgbmatrix\web2rgbmatrix.ino: In function 'void setup()':
C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi\src/WiFiType.h:35:22: error: 'ARDUINO_EVENT_WIFI_STA_CONNECTED' is not a member of 'system_event_id_t'
 #define WiFiEvent_t  system_event_id_t
                      ^
C:\Users\craig\Downloads\MiSTer_web2rgbmatrix-master (1)\MiSTer_web2rgbmatrix-master\arduino\web2rgbmatrix\web2rgbmatrix.ino:190:38: note: in expansion of macro 'WiFiEvent_t'
   WiFi.onEvent(WiFiStationConnected, WiFiEvent_t::ARDUINO_EVENT_WIFI_STA_CONNECTED);
                                      ^
C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi\src/WiFiType.h:35:22: error: 'ARDUINO_EVENT_WIFI_STA_GOT_IP' is not a member of 'system_event_id_t'
 #define WiFiEvent_t  system_event_id_t
                      ^
C:\Users\craig\Downloads\MiSTer_web2rgbmatrix-master (1)\MiSTer_web2rgbmatrix-master\arduino\web2rgbmatrix\web2rgbmatrix.ino:191:27: note: in expansion of macro 'WiFiEvent_t'
   WiFi.onEvent(WiFiGotIP, WiFiEvent_t::ARDUINO_EVENT_WIFI_STA_GOT_IP);
                           ^
C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi\src/WiFiType.h:35:22: error: 'ARDUINO_EVENT_WIFI_STA_DISCONNECTED' is not a member of 'system_event_id_t'
 #define WiFiEvent_t  system_event_id_t
                      ^
C:\Users\craig\Downloads\MiSTer_web2rgbmatrix-master (1)\MiSTer_web2rgbmatrix-master\arduino\web2rgbmatrix\web2rgbmatrix.ino:192:41: note: in expansion of macro 'WiFiEvent_t'
   WiFi.onEvent(WiFiStationDisconnected, WiFiEvent_t::ARDUINO_EVENT_WIFI_STA_DISCONNECTED);
                                         ^
C:\Users\craig\Downloads\MiSTer_web2rgbmatrix-master (1)\MiSTer_web2rgbmatrix-master\arduino\web2rgbmatrix\web2rgbmatrix.ino:215:34: error: call of overloaded 'String(uint64_t&)' is ambiguous
       sd_status = String(cardSize) + "MB";
                                  ^
In file included from C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/Arduino.h:146:0,
                 from C:\Users\craig\AppData\Local\Temp\arduino-sketch-921402039AF788F30B6663C867A0A210\sketch\web2rgbmatrix.ino.cpp:1:
C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/WString.h:71:18: note: candidate: String::String(double, unsigned char)
         explicit String(double, unsigned char decimalPlaces = 2);
                  ^
C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/WString.h:70:18: note: candidate: String::String(float, unsigned char)
         explicit String(float, unsigned char decimalPlaces = 2);
                  ^
C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/WString.h:69:18: note: candidate: String::String(long unsigned int, unsigned char)
         explicit String(unsigned long, unsigned char base = 10);
                  ^
C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/WString.h:68:18: note: candidate: String::String(long int, unsigned char)
         explicit String(long, unsigned char base = 10);
                  ^
C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/WString.h:67:18: note: candidate: String::String(unsigned int, unsigned char)
         explicit String(unsigned int, unsigned char base = 10);
                  ^
C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/WString.h:66:18: note: candidate: String::String(int, unsigned char)
         explicit String(int, unsigned char base = 10);
                  ^
C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/WString.h:65:18: note: candidate: String::String(unsigned char, unsigned char)
         explicit String(unsigned char, unsigned char base = 10);
                  ^
C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/WString.h:64:18: note: candidate: String::String(char)
         explicit String(char c);
                  ^
C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/WString.h:62:9: note: candidate: String::String(StringSumHelper&&)
         String(StringSumHelper &&rval);
         ^
C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/WString.h:61:9: note: candidate: String::String(String&&)
         String(String &&rval);
         ^
C:\Users\craig\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/WString.h:58:9: note: candidate: String::String(const String&)
         String(const String &str);
         ^
C:\Users\craig\Downloads\MiSTer_web2rgbmatrix-master (1)\MiSTer_web2rgbmatrix-master\arduino\web2rgbmatrix\web2rgbmatrix.ino: In function 'void WiFiStationDisconnected(system_event_id_t, system_event_info_t)':
C:\Users\craig\Downloads\MiSTer_web2rgbmatrix-master (1)\MiSTer_web2rgbmatrix-master\arduino\web2rgbmatrix\web2rgbmatrix.ino:321:32: error: 'union system_event_info_t' has no member named 'wifi_sta_disconnected'
   DBG_OUTPUT_PORT.println(info.wifi_sta_disconnected.reason);
                                ^

exit status 1

Compilation error: call of overloaded 'String(uint64_t&)' is ambiguous

**Comment by kconger** [comment]
You'll need to update to Arduino IDE 2.0 and ESP32 board package 2.0.4

**Comment by BulletMag** [comment]
That seemed to work, thanks

**Comment by BulletMag** [comment]
Everything flashed ok,
Script installed on the mister and updated, user.ini altered as per instructions.
Ip, Host name and SD card size is displayed on the matrix but then the screen saver starts and nothing else no matter what core I try.
Also it seems the gifs are loaded to the SD card on the mister rather than the one connected to the trinity.
Do I need to have installed tty2oled too ?
