### ISSUE TITLE
Nothing displayed

### ISSUE THREAD

**Issue by BulletMag** [kconger/MiSTer_web2rgbmatrix#5]
Everything flashed ok,
Script installed on the mister and updated, user.ini altered as per instructions.
Ip, Host name and SD card size is displayed on the matrix but then the screen saver starts and nothing else no matter what core I try.
Also it seems the gifs are loaded to the SD card on the mister rather than the one connected to the trinity.
Do I need to have installed tty2oled too ?

**Comment by BulletMag** [comment]
In addition to the above my web app appears different to the one shown in the documentation (mine is version 1.8 and I have removed the SD card at this point) 
![image](https://user-images.githubusercontent.com/34891230/193448800-2c1b02c4-d369-4595-aeeb-8d1b4b4957a5.png)

Mine appears to be missing everything under the screensaver setting... is it's just a 1.7 thing or am I missing something?

**Comment by kconger** [comment]
1.8 is the latest. If the SD card is not installed it hides things in the UI that would only be relevant if you had it installed.  The client IP and current gif only show when a web client requests a GIF and it's displayed.

You only need the tty2x service installed if you intend to use a serial connection.  If you are going to use tty2x then you need the SD card installed with the GIFs installed per the documentation.

The update script does pull a copy of the GIFs to your MiSTer this does not negate the step in the documentation where you load the GIFs onto the Matrix SD card.

**Comment by BulletMag** [comment]
I have the SD card set up as per the documentation it's just I had it removed when I took the screenshot,
When I have tried serial connection, there is a change in the display but the graphics are corrupt.
I'll try and remove the install and start from scratch later see if that makes a difference

**Comment by BulletMag** [comment]
I have the SD card set up as per the documentation it's just I had it removed when I took the screenshot,
When I have tried serial connection, there is a change in the display but the graphics are corrupt.
I'll try and remove the install and start from scratch later see if that makes a difference

**Comment by kconger** [comment]
I would start by manually testing the matrix from a web browser.  [http://rgbmatrix.local/localplay?file=MENU](http://rgbmatrix.local/localplay?file=MENU)

This is the same command that the web2rgbmmatrix service would make to load the Menu core GIF. If this works then I would focus on the MiSTer side of things.

**Comment by BulletMag** [comment]
I have the SD card set up as per the documentation it's just I had it removed when I took the screenshot,
When I have tried serial connection, there is a change in the display but the graphics are corrupt.
I'll try and remove the install and start from scratch later see if that makes a difference

**Comment by BulletMag** [comment]
Ok the web address you gave above works and the matrix displays the MiSTer menu gif so it seems the trinity side and SD are ok.
I deleted web2rgbmatrix from the mister SD and ran the script again
Copied all the options from system to user as is and it falls over when the script is ran again ...
![image](https://user-images.githubusercontent.com/34891230/193537204-3fb81d1d-f956-462d-8e82-0a0d8f620f21.jpeg)

I don't know what I'm doing wrong tbh

**Comment by venice1200** [comment]
Hi,
make a screenshot from your SD Card structure and tell us more about your used hardware.
Post your System and User INI as well.
Did your ESP get the same IP Adress at every boot?

Did you see a static or animated MENU Picture?

**Comment by BulletMag** [comment]
[web2rgbmatrix-system.txt](https://github.com/kconger/MiSTer_web2rgbmatrix/files/9697115/web2rgbmatrix-system.txt)
[web2rgbmatrix-user.txt](https://github.com/kconger/MiSTer_web2rgbmatrix/files/9697118/web2rgbmatrix-user.txt)

* above changed to TXT so i could post them here *

SD structure is FAT32 formatted card with gif folder on the root and agif folder inside that

I have an ESP Trinity connected directly to the RGB panels

The same IP is assigned on each boot

When pointing my browser at http://rgbmatrix.local/localplay?file=MENU I see an animated Mister logo followed by the static logo

**Comment by blackboxembedded** [comment]
You can't use rgbmatrix.local on your MiSTer as it doesn't support MDNS resolution.  You will need to use your matrix IP or setup a DNS entry if your network architecture allows it.

HOSTNAME="192.168.5.215"

**Comment by kconger** [comment]
As noted in the README rgbmatrix.local won't resolve on the MiSTer as it doesn't support MDNS resolution. You should use your matrix IP.

HOSTNAME="192.168.5.215"

**Comment by BulletMag** [comment]
Ok changed the hostname to the assigned IP (192.168.5.215)
Ran the script and got an error...
![image](https://user-images.githubusercontent.com/34891230/193598834-30a106e3-561b-4e9a-8260-cf25a1d79da5.jpeg)

**Comment by kconger** [comment]
I noticed you had debug turned on, does /tmp/web2rgbmatrix have any additional messages in it?

**Comment by BulletMag** [comment]
Unfortunately not, I enabled this in the hope it would provide a solution to where I was going wrong no log at all seems to have been made

**Comment by kconger** [comment]
> 
> SD structure is FAT32 formatted card with gif folder on the root and agif folder inside that

Does your matrix SD have the 'gifs' and 'agifs' folder at its root?

**Comment by BulletMag** [comment]
actually I managed to find the log file, not much help though ...

---------- web2rgbmatrix Debuglog ----------
Read CORENAME: -MENU-
Requesting matrix to display GIF from its SD Card File
Unknown error requesting MENU GIF on matrix
Read CORENAME: -MENU-
Requesting matrix to display GIF from its SD Card File
Unknown error requesting MENU GIF on matrix

My SD card has just the gifs folder and the agif folder is inside that

**Comment by kconger** [comment]
Probably not the problem but both the 'gifs' and 'agifs' folder need to be at the root of your SD card.  Below each are the letter/number directories with the GIFs within them. The README shows the structure you should see.

**Comment by BulletMag** [comment]
Yeah just realised that when i looked at the picture again, 
moved agif folder to the root and alas still get the same error.

I dont understand how I can address the matrix directly via the browser, so this shows the file structure is ok (I guess) its just why the mister cant trigger it is baffling me.

**Comment by kconger** [comment]
Can you try this command from your MiSTer:
`curl http://192.168.5.215/localplay?file=MENU`

**Comment by BulletMag** [comment]
I'm not sure where to enter that command, I don't recall terminal access on my mister

**Comment by kconger** [comment]
You can enter it in the console, switching to the console is F9 I believe or SSH into your MiSTer.

**Comment by BulletMag** [comment]
Ok used putty to ssh in (first time 😁) 
Menu appeared !!!

**Comment by BulletMag** [comment]
YAY !  
I appear to have resolved the issue,
I decided to delete the entire web2rgbmatrix folder and the script too

Re-downloaded the entire package from github again and unpacked,

Coped the web2rgbmatrix folder from the linux folder to the fat folder on the mister and created the web2rgbmatrix-user.ini 

Copied both the update scripts to the Scripts folder on the mister

Ran update_web2rgbmatrix_script 

Now appears to be working fine on all the cores I have tested so far.

Thanks for your help

**Comment by kconger** [comment]
Thats great!
