### ISSUE TITLE
Enhancement - Choose static or animated gifs and allow multiple web2rgbmatrix

### ISSUE THREAD

**Issue by siffland** [kconger/MiSTer_web2rgbmatrix#8]
Maybe i missed it in the documentation, is there a way to just choose just animated or just static gifs?  Also is there a way to have more than one web2rgbmatrix attached to the mister and updated with different options?  Currently I just deleted the animated gifs to force static, but that is not ideal.

It would be neat in my set up to have one web2rgbmatrix with the static gifs and another with animated (if available).

**Comment by kconger** [comment]
The current way as you discovered is to remove the GIFs you don't want.  It be easy enough to add an option though, I will add this in the future.

Supporting two or more displays, is a fringe case and have no plans to add it.  You could modify the service script and/or run two instances of it.

**Comment by kconger** [comment]
Added options for GIF playback from SD. 07702a19cd61bbeb20eab5818821069e26ed19a3
